[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
exclude_lints = ["mixed-case-function", "pascal-case-struct"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
